### ISSUE TITLE
How do I configure this plugin to process only my amp-html pages?

### ISSUE THREAD

**Issue by michrome** [ampproject/eleventy-plugin-amp#10]
Hi

My project contains a mix of html pages and amp-html pages. How do I configure this plugin to process only my amp-html pages?

Ideally I'd want to process only files/directories matching a regular expression e.g. `*-amp.html` or `_site/*/amp/*`.

Thanks!

**Comment by patrickkettner** [comment]
you can't within the plugin itself, currently. [It will run on any `.html`](https://github.com/ampproject/eleventy-plugin-amp/blob/7766995bd21530b206b6104cf0149774c85e6a3b/src/transforms/ampTransform.js#L23-L25
). To kludge around this today, you would need to vary your `.eleventy` to add or not add the plugin, and build the site twice :/

if @sebastianbenz is amenable to it, I can PR a change to config something like a regex filter that can be passed to the transform

**Comment by sebastianbenz** [comment]
Regex filter sounds like a good option. @michrome what would be your preferred way to handle this case?

**Comment by michrome** [comment]
Thanks for the replies.

A regex would be awesome, particularly if it also checked the directory name as well as the file name, because I think it's common for the same content to be built as `/content-slug/index.html` and `/content-slug/amp/index.html`.

@patrickkettner, tangentially related: your "build it twice" suggestion has popped up before, when someone asked if they could [use the same content with two different layouts (HTML and AMP-HTML)](https://github.com/11ty/eleventy/issues/712). I suggested [using JavaScript front matter](https://github.com/11ty/eleventy/issues/712#issuecomment-599274792) and [two builds](https://github.com/michrome/eleventy-amp-example/blob/master/netlify.toml).

**Comment by sebastianbenz** [comment]
Made a new release 0.2.0 which includes this fix.
