### ISSUE TITLE
outputPath.endsWith check fails with permalink: false

### ISSUE THREAD

**Issue by SergeyRe** [ampproject/eleventy-plugin-amp#103]
Problem specific to some  plugings ( incl. amp-plugin) due to not taking into accout next moment described here
[page.outputPath and page.url can sometimes be false, not strings](https://github.com/11ty/11ty-website/pull/991)
[More details and discussion of this issue](https://github.com/11ty/eleventy/issues/653)
Sure this plugin have to be modified

**Comment by thedalewilliams** [comment]
I had this issue as well while using pagination and having permalink false in the front matter.

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@ampproject/eleventy-plugin-amp@0.5.7` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@ampproject/eleventy-plugin-amp/src/helpers/AmpConfig.js b/node_modules/@ampproject/eleventy-plugin-amp/src/helpers/AmpConfig.js
index 3b572e1..a3eb25d 100644
--- a/node_modules/@ampproject/eleventy-plugin-amp/src/helpers/AmpConfig.js
+++ b/node_modules/@ampproject/eleventy-plugin-amp/src/helpers/AmpConfig.js
@@ -30,7 +30,7 @@ const AmpConfig = (providedOptions) => {
     throw new Error(`filter needs to be a valid RegExp, provided : ${options.filter}`);
   }
 
-  options.isAmp = (path) => path.endsWith('.html') && options.filter.test(path);
+  options.isAmp = (path) => path && path.endsWith('.html') && options.filter.test(path);
 
   if (providedOptions.optimizeImages !== false && !providedOptions.imageOptimizer) {
     options.imageOptimizer = ImageOptimizer.create(options);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>
