### ISSUE TITLE
Could not load content

### ISSUE THREAD

**Issue by jakefuller1** [ampproject/eleventy-plugin-amp#106]
If I look at Chrome sources, I see this error: Could not load content for https://raw.githubusercontent.com/ampproject/amphtml/2110212130002/build/amp-ad-0.1.css.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE) and others from github ...
Is this normal? I don't use github.
If I want to host amp runtime, where do I put google analytics json, so analytics works?

**Comment by patrickkettner** [comment]
What is the URL? Are you using the eleventy plugin?

**Comment by jakefuller1** [comment]
Yes this is eleventy plugin.  https://www.centralhome.com/amp/Four-legged-Attitude.htm
My main concern is getting google analytics to work. Failed to load resource: the server responded with a status of 406 . Server has no problem with other json or jsonld files. Not sure what to put in googleanalytics.json

**Comment by patrickkettner** [comment]
I am not seeing the 404 you originally reported, nor do I think it would have anything to do with this plugin.
`googleanalytics.json` is not a file required by this plugin, there is nothing to do with google analytics in it. I am sorry to not be of more help, but the code tripping you up does not seem to be in this repo. 

If you can share the source of the eleventy page I may be able to point you in the right direction, but for now I am going to close the issue as it doesn't seem related to this repo.

**Comment by jakefuller1** [comment]
![image](https://user-images.githubusercontent.com/40129367/141347247-1440c031-4760-4445-90a7-0398c19a76ba.png)

googleanalytics.json is generated by this plugin, if you self-host. Analytics works if you don't self-host.

const ampPlugin = require('@ampproject/eleventy-plugin-amp');

  eleventyConfig.addPlugin(ampPlugin, {
    ampCache: false,
    downloadAmpRuntime: true,
    ampRuntimeHost:
      process.env.ENV === 'prod' ? 'https://www.centralhome.com' : 'https://www.centralhome.com',
    experimentEsm: false,
    experimentImg: false,
    validation: false,
    imageOptimization: false,
  });

**Comment by patrickkettner** [comment]
thanks for the update!
Few things - the screenshot you sent shows source panel of the page. What is happening is AMP is trying to load the [sourcemap](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/SourceMap) for the various files to make local debugging easier. In this case, there isn't a sourcemap for the css file related to [amp-ad](https://amp.dev/documentation/components/amp-ad/). It will not impact any part of your site. the file is purely for debugging.
This also is unrelated to google analytics. This plugin does not load or modify the analytics of the page. If `googleanalytics.json` is a file you are calling with the [optional config](https://amp.dev/documentation/components/amp-analytics/#config-(optional)) attribute on a `<amp-analytics>` module, the contents would be the same as the inline json you would normally write for `<amp-analytics>`. You can read more about that [here](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/tracking-engagement/#step-2:-add-configuration-code)

**Comment by jakefuller1** [comment]
Thank you re clarification source map.
I'm still confused re analytics. I have same for self host or non host (I am not calling googleanalytics.json,. plug in seems to do that!)
<amp-analytics type="googleanalytics"><script type="application/json">{"vars": { "account": "UA-xxxxx-2", "config": { "site_speed_sample_rate": 100 }},"triggers": {"trackPageview": { "on": "visible", "request": "pageview" },"capture CLS": {"on": "visible","request": "event","vars": {"eventCategory": "Web Vitals","eventAction": "CLS","eventLabel": "${clientId}-${pageViewId}-CLS","eventValue": "$CALC(${cumulativeLayoutShift},1000,multiply,true)"}},"capture FID": {"on": "visible","request": "event","vars": {"eventCategory": "Web Vitals","eventAction": "FID","eventLabel": "${clientId}-${pageViewId}-FID","eventValue": "$CALC(${firstInputDelay},0,add,true)" }},"capture LCP": {"on": "visible","request": "event","vars": {"eventCategory": "Web Vitals","eventAction": "LCP","eventLabel": "${clientId}-${pageViewId}-LCP", "eventValue": "$CALC(${largestContentfulPaint},0,add,true)"}}}}</script></amp-analytics>
Works on not self-host but using self host
<html>
<body>


[AmpAnalytics <unknown id>] Error loading vendor config: https://www.centralhome.com/rtv/012110212130002/v0/analytics-vendors/googleanalytics.json Error: HTTP error 406​​​at ia (https://www.centralhome.com/rtv/012110212130002/v0.mjs:1:1568) at ub.createError (https://www.centralhome.com/rtv/012110212130002/v0.mjs:1:13030) at https://www.centralhome.com/rtv/012110212130002/v0.mjs:3:84759 at new Promise (<anonymous>) at Mg (https://www.centralhome.com/rtv/012110212130002/v0.mjs:3:84701) at https://www.centralhome.com/rtv/012110212130002/v0.mjs:3:85536 at async Promise.all (index 1)
--
v0.mjs:1 | [AmpAnalytics <unknown id>] Ignoring request for event. Request string not found: event
v0.mjs:1 | [AmpAnalytics <unknown id>] Ignoring request for event. Request string not found: event
v0.mjs:1 | [AmpAnalytics <unknown id>] Ignoring request for event. Request string not found: event
v0.mjs:1 | [AmpAnalytics <unknown id>] Ignoring request for event. Request string not found: pageview
/rtv/012110212130002…gleanalytics.json:1 | Failed to load resource: the server responded with a status of 406 ()


</body>
</html>
