### ISSUE TITLE
Customize the amp-img layout attribute value

### ISSUE THREAD

**Issue by codysaylor** [ampproject/eleventy-plugin-amp#58]
This plugin does a lot of optimizing for the image `<amp-img>` element, which is great, however I'd like to be able to customize the layout option for `<amp-img>` so we can set it to "responsive" instead of "intrinsic".

While we can manually add `<amp-img>`, it won't do all the 11ty / amp optimizations. I'd like to either be able to pass in attributes in the `<img>` tag, like `<img src="/path/to/file.jpg" alt="Cat" layout="responsive">` or similar for the markdown images.

**Comment by sebastianbenz** [comment]
Hm. Would an `amp-img` shortcode help here? 

I don't quite understand what you mean by "While we can manually add <amp-img>, it won't do all the 11ty / amp optimizations." Can you elaborate?

**Comment by codysaylor** [comment]
Yes, I think a shortcode would be great if it could still utilize the image optimizations that currently exist. If I add `<amp-img>` directly, I have the option to use the `layout="responsive"` attribute, but wouldn't be optimized or use the srcset generation feature, unless I am wrong about that.

> The plugin offers automated image optimization and srcset generation. The plugin uses AMP Optimizer's built-in srcset generation and eleventy-img for image resizing.
> [https://github.com/ampproject/eleventy-plugin-amp#image-optimization](https://github.com/ampproject/eleventy-plugin-amp#image-optimization)

**Comment by sebastianbenz** [comment]
srcset generation still should work if you use amp-img. Shortcode would just be a more convenient way to define the img.

**Comment by codysaylor** [comment]
Right you are. My bad - I don't think a shortcode is necessary.

Thank you for this plugin!
